export const countries = [
  { value: "US", label: "United States (+1)" },
  { value: "CA", label: "Canada (+1)" },
  { value: "GB", label: "United Kingdom (+44)" },
  { value: "AU", label: "Australia (+61)" },
  { value: "DE", label: "Germany (+49)" },
  { value: "FR", label: "France (+33)" },
  { value: "IT", label: "Italy (+39)" },
  { value: "JP", label: "Japan (+81)" },
  { value: "CN", label: "China (+86)" },
  { value: "IN", label: "India (+91)" },
  { value: "BR", label: "Brazil (+55)" },
  { value: "RU", label: "Russia (+7)" },
  { value: "ZA", label: "South Africa (+27)" },
  { value: "KR", label: "South Korea (+82)" },
  { value: "MX", label: "Mexico (+52)" },
  { value: "ES", label: "Spain (+34)" },
  { value: "NL", label: "Netherlands (+31)" },
  { value: "CH", label: "Switzerland (+41)" },
  { value: "SE", label: "Sweden (+46)" },
  { value: "SG", label: "Singapore (+65)" },
];

export const languages = [
  { value: "en", label: "English" },
  { value: "es", label: "Español" },
  { value: "fr", label: "Français" },
  { value: "de", label: "Deutsch" },
  { value: "it", label: "Italiano" },
  { value: "pt", label: "Português" },
  { value: "ja", label: "日本語" },
  { value: "zh", label: "中文" },
  { value: "ko", label: "한국어" },
];
